name: Publish on main

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: https://registry.npmjs.org
          scope: '@limeyfy'
          always-auth: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Ensure unique version (bump patch if published)
        id: version
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const cp = require('child_process');
          const pkg = JSON.parse(fs.readFileSync('package.json','utf8'));
          const name = pkg.name;
          const current = pkg.version;
          let published = [];
          try {
            const out = cp.execSync(`npm view ${name} versions --json`, { encoding: 'utf8' }).trim();
            published = JSON.parse(out || '[]');
          } catch (e) {
            // package may not exist yet; continue
          }
          const exists = Array.isArray(published) && published.includes(current);
          let next = current;
          if (exists) {
            cp.execSync('npm version patch --no-git-tag-version', { stdio: 'inherit' });
            next = JSON.parse(fs.readFileSync('package.json','utf8')).version;
            console.log(`Bumped version to ${next}`);
            cp.execSync(`git add package.json`, { stdio: 'inherit' });
            cp.execSync(`git commit -m "chore(release): bump version to ${next}"`, { stdio: 'inherit' });
            cp.execSync(`git push origin HEAD:main`, { stdio: 'inherit' });
          } else {
            console.log(`Using version ${current}`);
          }
          const out = process.env.GITHUB_OUTPUT;
          if (out) fs.appendFileSync(out, `version=${next}\n`);
          NODE

      - name: Create tag
        run: |
          VERSION=${{ steps.version.outputs.version }}
          if [ -z "$VERSION" ]; then VERSION=$(node -p "require('./package.json').version"); fi
          echo "Tagging v$VERSION"
          git tag -a "v$VERSION" -m "v$VERSION" || echo "Tag exists"
          git push origin "v$VERSION" || echo "Tag push skipped"

      - name: Configure npm auth (npmjs)
        if: env.NODE_AUTH_TOKEN != ''
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc
          npm whoami || true

      - name: Publish to npm (public)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "@limeyfy:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> ~/.npmrc
          npm publish --registry=https://npm.pkg.github.com

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

